name: main
on: [ pull_request, workflow_dispatch ]

jobs:
  android:
    runs-on: macos-11
    timeout-minutes: 30
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.3.5
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Run integration tests
        # More info on https://github.com/ReactiveCircus/android-emulator-runner
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          profile: Nexus 6
          script: flutter drive --driver test_driver/integration_test.dart --target=integration_test/test.dart
      - name: upload screenshots
        uses: actions/upload-artifact@master
        with:
          name: screenshots
          path: screenshots/*
